apps/courses/views.py
from flask import Blueprint, session, render_template, request, flash, url_for, redirect
import MySQLdb

courses = Blueprint(
    "courses",
    __name__,
    template_folder="templates",
)

def str_rm_null(str):
    if str != None:
        return str + '。'
    return ''

@courses.route("/course/")
def list_courses():
    # 顯示可選課表
    # 顯示關注清單，取消關注
    # 選課，需滿足加選條件
    
    if 'sid' not in session:
        return redirect("/login/")
    
    conn = MySQLdb.connect(host="127.0.0.1",
                           user="hj",
                           passwd="test1234",
                           db="testdb")

    course_query = f"""
        SELECT course_id, cname, tname, compulsory, credit, GROUP_CONCAT(CONCAT(time_id, " ", loc_name) SEPARATOR '<br>') AS Time, IFNULL(TakeCount, 0), capicity, CONCAT(COALESCE(Duplicate_Time, ''), '<br>', COALESCE(Duplicate_Name, ''), '<br>', COALESCE(More_Credit, ''), '<br>', COALESCE(Follows, '')) AS reason, cgrade 
        FROM
            (SELECT course_id, cname, tname, compulsory, credit, TakeCount, capicity, cgrade,
                    CASE
                        WHEN (
                            SELECT COUNT(*) FROM section 
                            WHERE course.course_id=section.course_id
                            AND time_id 
                            IN (SELECT time_id FROM takes LEFT JOIN section USING (course_id) WHERE sid='{session['sid']}')
                        ) > 0
                        THEN '衝堂'
                    END AS Duplicate_Time,
                    CASE
                        WHEN cname IN (SELECT cname FROM takes LEFT JOIN course USING (course_id) WHERE sid = '{session['sid']}') 
                        THEN '已選同名課程'
                    END AS Duplicate_Name,
                    CASE
                        WHEN (SELECT SUM(credit) FROM takes LEFT JOIN course USING (course_id) WHERE sid = '{session['sid']}') + credit > 30
                        THEN '加選後，學分數超過30'
                    END AS More_Credit,
                    CASE
                        WHEN course_id IN (SELECT course_id FROM follows WHERE sid = '{session['sid']}')
                        THEN '已關注'
                    END AS Follows
                FROM Course
                -- 加入老師名稱
                LEFT JOIN Teacher USING (tid)
                -- 加入已選人數
                LEFT JOIN (SELECT course_id, COUNT(*) AS TakeCount FROM Takes GROUP BY course_id) AS CourseTakeCount USING (course_id)
                -- 檢查科系
                WHERE course.dept_name='{session['dept_name']}'
                -- 還沒選課
                AND course_id NOT IN (SELECT course_id FROM takes WHERE sid = '{session['sid']}')) AS Temp
        LEFT JOIN section USING (course_id)
        GROUP BY course_id
    """

    cursor = conn.cursor()
    cursor.execute(course_query)

    # print(cursor.fetchall())
    return render_template("course.html", 
                           course_list=cursor.fetchall())

@courses.route('/course/select/', methods=['POST'])
def select_course():
    if 'sid' not in session:
        return redirect("/login/")
    
    conn = MySQLdb.connect(host="127.0.0.1",
                           user="hj",
                           passwd="test1234",
                           db="testdb")
    
    course_id = request.values.get("course_id", None)
    action = request.values.get("action", None)
    
    query = f"""
        SELECT 
            CASE
                WHEN IFNULL(TakeCount, 0) >= Capicity
                THEN '已滿'
            END AS Available,
            CASE
                WHEN cname IN (SELECT cname FROM takes LEFT JOIN course USING (course_id) WHERE sid = '{session['sid']}') 
                THEN '已選同名課程'
            END AS Duplicate_Name,
            CASE
                WHEN (
                    SELECT COUNT(*) FROM section 
                    WHERE course.course_id=section.course_id
                    AND time_id 
                    IN (SELECT time_id FROM takes LEFT JOIN section USING (course_id) WHERE sid='{session['sid']}')
                ) > 0
                THEN '衝堂'
            END AS Duplicate_Time,
            CASE
                WHEN (SELECT SUM(credit) FROM takes LEFT JOIN course USING (course_id) WHERE sid = '{session['sid']}') + credit > 30
                THEN '加選後，學分數超過30'
            END AS More_Credit,
            CASE
                WHEN course.dept_name!='{session['dept_name']}'
                THEN '不同科系'
            END AS Different_Dept,
            CASE
                WHEN course_id IN (SELECT course_id FROM follows WHERE sid = '{session['sid']}')
                THEN '已關注'
            END AS Follows,
            CASE
                WHEN course_id IN (SELECT course_id FROM takes WHERE sid = '{session['sid']}')
                THEN '已選課'
            END AS Takes
        -- 加入已選人數
        FROM course
        LEFT JOIN (SELECT course_id, COUNT(*) AS TakeCount FROM Takes GROUP BY course_id) AS CourseTakeCount USING (course_id)
        WHERE course_id='{course_id}'
    """
    # print(query)

    cursor = conn.cursor()
    cursor.execute(query)

    result = cursor.fetchall()[0]

    if action == '加選' and result[0]==None and result[1]==None and result[2]==None and result[3]==None and result[4]==None and result[5]==None and result[6]==None:
        select_query = f"""
            INSERT INTO takes (sid, course_id) VALUES
            ('{session['sid']}', '{course_id}');
        """
        cursor.execute(select_query)
        conn.commit()

        return redirect("/course/?msg='成功加選'")
    elif action == '加選' and result[6]!=None:
        return redirect("/course/?msg='不能加選已選課程'")
    elif action == '加選':
        return redirect(f"/course/?msg='{str_rm_null(result[0])}{str_rm_null(result[1])}{str_rm_null(result[2])}{str_rm_null(result[3])}{str_rm_null(result[4])}'")
    elif action == '關注' and result[0]!=None and result[1]==None and result[2]==None and result[3]==None and result[4]==None and result[5]==None and result[6]==None:
        select_query = f"""
            INSERT INTO follows (sid, course_id) VALUES
            ('{session['sid']}', '{course_id}');
        """
        cursor.execute(select_query)
        conn.commit()

        return redirect("/course/?msg='成功關注'")
    elif action == '關注' and result[6]!=None:
        return redirect("/course/?msg='不能關注已選課程'")
    elif action == '關注' and result[0]==None:
        return redirect("/course/?msg='不能關注未滿課程'")
    elif action == '關注':
        return redirect(f"/course/?msg='{str_rm_null(result[1])}{str_rm_null(result[2])}{str_rm_null(result[3])}{str_rm_null(result[4])}{str_rm_null(result[5])}'")
    elif action == '取消關注':
        select_query = f"""
            DELETE FROM follows WHERE sid='{session['sid']}' AND course_id='{course_id}';
        """
        cursor.execute(select_query)
        conn.commit()

        return redirect("/course/?msg='成功取消關注'")
    else:
        return redirect("/course/")

apps/timetable/views.py
from flask import Blueprint, session, render_template, redirect, request, flash
import MySQLdb

timetable = Blueprint(
    "timetable",
    __name__,
    template_folder="templates",
)

@timetable.route("/timetable/")
def my_timetable():
    if 'sid' not in session:
        return redirect("/login/")
    
    conn = MySQLdb.connect(host="127.0.0.1",
                           user="hj",
                           passwd="test1234",
                           db="testdb")
    
    query_courses = f"""
    SELECT
        section.time_id AS 時間,
        course.course_id AS 課程代號,
        course.cname AS 課程名稱,
        teacher.tname AS 老師姓名,
        section.loc_name AS 課程地點,
        course.compulsory AS 必選修,
        course.credit AS 學分
    FROM
        takes
    LEFT JOIN
        section ON takes.course_id = section.course_id
    LEFT JOIN
        course ON takes.course_id = course.course_id
    LEFT JOIN
        teacher ON course.tid = teacher.tid
    WHERE
        takes.sid = '{session['sid']}'
    """

    cursor = conn.cursor()
    cursor.execute(query_courses)
    courses_result = cursor.fetchall()

    total_query = f"""
    SELECT IFNULL(SUM(course.credit) , 0)
    FROM takes 
    LEFT JOIN course ON takes.course_id = course.course_id 
    WHERE sid = '{session['sid']}'
    """
    cursor.execute(total_query)
    total_credit = cursor.fetchone()[0]

    return render_template("timetable.html", table=courses_result, total_credit=total_credit)

@timetable.route("/timetable/withdraw/<course_id>", methods=["POST"])
def withdraw_course(course_id):
    if 'sid' not in session:
        return redirect("/login/")

    conn = MySQLdb.connect(host="127.0.0.1",
                           user="hj",
                           passwd="test1234",
                           db="testdb")

    credit_query = f"""
    SELECT IFNULL(SUM(course.credit) , 0)
    FROM takes 
    LEFT JOIN course ON takes.course_id = course.course_id 
    WHERE sid = '{session['sid']}' AND takes.course_id != '{course_id}'
    """
    cursor = conn.cursor()
    cursor.execute(credit_query)
    total_credit = cursor.fetchone()[0]

    if total_credit < 9:
        return redirect("/timetable/?msg='學分總數<9，退選失敗'")
    
    delete_query = f"""
    DELETE FROM takes
    WHERE sid = '{session['sid']}' AND course_id = '{course_id}'
    """    

    cursor.execute(delete_query)
    conn.commit()

    takes_count_query = f"""
    SELECT COUNT(*) AS take_count FROM takes WHERE course_id='{course_id}';
    """
    capicity_query = f"""
    SELECT capicity FROM course WHERE course_id='{course_id}';
    """
    get_random_followers_query = f"""
    SELECT follows.sid, dept_name FROM follows LEFT JOIN student ON student.sid=follows.sid WHERE course_id='{course_id}' ORDER BY RAND() LIMIT 1
    """
    while True:
        cursor.execute(takes_count_query)
        takes_count = cursor.fetchall()[0][0]
        cursor.execute(capicity_query)
        capicity = cursor.fetchall()[0][0]
        if takes_count >= capicity:
            break
        
        cursor.execute(get_random_followers_query)
        stu = cursor.fetchall()
        if len(stu) > 0:
            sid = stu[0][0]
            dept_name = stu[0][1]

            delete_followers = f"""
            DELETE FROM follows WHERE sid='{sid}' AND course_id='{course_id}'
            """
            cursor.execute(delete_followers)
            conn.commit()

            add_query = f"""
            SELECT 
                CASE
                    WHEN IFNULL(TakeCount, 0) >= Capicity
                    THEN '已滿'
                END AS Available,
                CASE
                    WHEN cname IN (SELECT cname FROM takes LEFT JOIN course USING (course_id) WHERE sid = '{sid}') 
                    THEN '已選同名課程'
                END AS Duplicate_Name,
                CASE
                    WHEN (
                        SELECT COUNT(*) FROM section 
                        WHERE course.course_id=section.course_id
                        AND time_id 
                        IN (SELECT time_id FROM takes LEFT JOIN section USING (course_id) WHERE sid='{sid}')
                    ) > 0
                    THEN '衝堂'
                END AS Duplicate_Time,
                CASE
                    WHEN (SELECT SUM(credit) FROM takes LEFT JOIN course USING (course_id) WHERE sid = '{sid}') + credit > 30
                    THEN '加選後，學分數超過30'
                END AS More_Credit,
                CASE
                    WHEN course.dept_name!='{dept_name}'
                    THEN '不同科系'
                END AS Different_Dept,
                CASE
                    WHEN course_id IN (SELECT course_id FROM follows WHERE sid = '{sid}')
                    THEN '已關注'
                END AS Follows,
                CASE
                    WHEN course_id IN (SELECT course_id FROM takes WHERE sid = '{sid}')
                    THEN '已選課'
                END AS Takes
            -- 加入已選人數
            FROM course
            LEFT JOIN (SELECT course_id, COUNT(*) AS TakeCount FROM Takes GROUP BY course_id) AS CourseTakeCount USING (course_id)
            WHERE course_id='{course_id}'
            """
            cursor.execute(add_query)
            print(cursor.fetchall())
            cursor.execute(add_query)
            result = cursor.fetchall()[0]
            if result[0]==None and result[1]==None and result[2]==None and result[3]==None and result[4]==None and result[5]==None and result[6]==None:
                select_query = f"""
                    INSERT INTO takes (sid, course_id) VALUES
                    ('{sid}', '{course_id}');
                """
                cursor.execute(select_query)
                conn.commit()
        else:
            break
    conn.close()

    return redirect("/timetable/?msg='成功退選'")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <style>
        /* Basic styling for the navigation bar */
        .navbar {
            display: flex; /* Use flexbox layout */
            justify-content: space-between; /* Distribute space between elements */
            align-items: center; /* Vertically center items */
            background-color: #333; /* Dark background color */
            font-family: Arial, sans-serif; /* Font style for the text */
            padding: 0 10px; /* Padding on the sides */
        }
    
        .personal-info {
            color: white; /* Text color */
        }
    
        /* Navigation links styling */
        .navbar-content {
            display: flex;
            flex-grow: 1; /* Allows navbar-content to take up any available space */
            justify-content: flex-end; /* Align links to the right */
        }
    
        .navbar a {
            color: white; /* Text color */
            text-align: center;
            padding: 14px 10px; /* Padding for each link */
            text-decoration: none; /* Removes underline from links */
        }
    
        /* Changes color on hover */
        .navbar a:hover {
            background-color: #ddd;
            color: black;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <div class="personal-info">
            <span>{{session.sid}} {{session.sname}} {{session.dept_name}} {{session.sgrade}}年級</span>
        </div>
        <div class="navbar-content">
            <a href={{ url_for('courses.list_courses') }}>加選</a>
            <a href={{ url_for('timetable.my_timetable') }}>課表</a>
            <a href={{ url_for('auth.logout') }}>登出</a>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/course.html
{% extends 'base.html' %}

{% block title %}
選課
{% endblock %}

{% block content %}

<h3>可選課程</h3>
<table style="border-spacing: 10px;">
    <tr style="text-align: left;">
        <th>課程代號</th>
        <th>課程名稱</th>
        <th>老師</th>
        <th>必修課</th>
        <th>學分</th>
        <th>地點</th>
        <th>已選人數/可選人數</th>
        <th>功能</th>
    </tr>
    {% for course in course_list %}
        {% if course[8] == '<br><br><br>' %}
            <tr>
                <td>{{ course[0] }}</td>
                <td>{{ course[1] }}</td>
                <td>{{ course[2] }}</td>
                {% if course[3] == 1 %}
                <td>{{ course[9] }}年級必修</td>
                {% else %}
                <td>選修</td>
                {% endif %}
                <td>{{ course[4] }}</td>
                {% autoescape false %}
                <td>{{ course[5] }}</td>
                {% endautoescape %}
                {% if course[6] != None %}
                <td>{{course[6]}}/{{ course[7]}}</td>
                {% else %}
                <td>0/{{ course[7] }}</td>
                {% endif %}
                <td>
                    <form action="/course/select/" method="post">
                        <input type="hidden" name="course_id" value="{{ course[0] }}" />
                        {% if course[6] == None or course[6] < course[7] %}
                        <input type="submit" name="action" value="加選">
                        {% else %}
                        <input type="submit" name="action" value="關注">
                        {% endif %}
                    </form>
                </td>
            </tr>
        {% endif %}
    {% endfor %}
</table>

<hr>

<h3>已關注課程</h3>
<table style="border-spacing: 10px;">
    <tr style="text-align: left;">
        <th>課程代號</th>
        <th>課程名稱</th>
        <th>老師</th>
        <th>必修課</th>
        <th>學分</th>
        <th>地點</th>
        <th>已選人數/可選人數</th>
        <th>功能</th>
    </tr>
    {% for course in course_list %}
        {% if course[8] == '<br><br><br>已關注' %}
            <tr>
                <td>{{ course[0] }}</td>
                <td>{{ course[1] }}</td>
                <td>{{ course[2] }}</td>
                {% if course[3] == 1 %}
                <td>必修</td>
                {% else %}
                <td>選修</td>
                {% endif %}
                <td>{{ course[4] }}</td>
                {% autoescape false %}
                <td>{{ course[5] }}</td>
                {% endautoescape %}
                {% if course[6] != None %}
                <td>{{course[6]}}/{{ course[7]}}</td>
                {% else %}
                <td>0/{{ course[7] }}</td>
                {% endif %}
                <td>
                    <form action="/course/select/" method="post">
                        <input type="hidden" name="course_id" value="{{ course[0] }}" />
                        <input type="submit" name="action" value="取消關注">
                    </form>
                </td>
            </tr>
        {% endif %}
    {% endfor %}
</table>

<hr>

<h3>本系不可選課程</h3>
<table style="border-spacing: 10px;">
    <tr style="text-align: left;">
        <th>課程代號</th>
        <th>課程名稱</th>
        <th>老師</th>
        <th>必修課</th>
        <th>學分</th>
        <th>地點</th>
        <th>已選人數/可選人數</th>
        <th>原因</th>
    </tr>
    {% for course in course_list %}
        {% if course[8] != '<br><br><br>' and course[8] != '<br><br><br>已關注' %}
            <tr>
                <td>{{ course[0] }}</td>
                <td>{{ course[1] }}</td>
                <td>{{ course[2] }}</td>
                {% if course[3] == 1 %}
                <td>必修</td>
                {% else %}
                <td>選修</td>
                {% endif %}
                <td>{{ course[4] }}</td>
                {% autoescape false %}
                <td>{{ course[5] }}</td>
                {% endautoescape %}
                {% if course[6] != None %}
                <td>{{course[6]}}/{{ course[7]}}</td>
                {% else %}
                <td>0/{{ course[7] }}</td>
                {% endif %}
                {% autoescape false %}
                <td>{{ course[8] }}</td>
                {% endautoescape %}
            </tr>
        {% endif %}
    {% endfor %}
</table>

<script>
    window.onload = () => {
        const queryString = window.location.search;
        const urlParams = new URLSearchParams(queryString);
        if (urlParams.get('msg') != null) {
            alert(urlParams.get('msg'));
        }
    }
</script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Hello</h1>
    <form action={{ url_for('auth.login') }} method="POST">
        <fieldset>
            <legend>Login</legend>
            <label>ID: </label>
            <input type="text" name="username" /><br><br>
            <label>Password: </label>
            <input type="password" name="password" /><br><br>
            <input type="submit" value="Login" />
        </fieldset>
    </form>
</body>
</html>

templates/timetable.html
{% extends 'base.html' %}

{% block title %}
我的課表
{% endblock %}

{% block content %}
<style>
    .container {
        margin-top: 20px;
    }

    .table-container {
        max-width: 800px;
        margin: 0 auto;
    }

    .table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
        text-align: left;
    }

    .table th,
    .table td {
        padding: 8px;
        border: 1px solid #ddd;
    }

    .table th {
        background-color: #f2f2f2;
    }

    .table tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .btn-withdraw {
        background-color: #dc3545;
        color: #fff;
        border: none;
        padding: 5px 10px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .btn-withdraw:hover {
        background-color: #c82333;
    }

    .table-container {
        margin-left: 0;
    }

    .total-credit {
        margin-top: 20px;
    }
</style>

<div class="container">
    <h1 class="text-center">我的課表</h1>
    {% for message in get_flashed_messages(with_categories=true) %}
    <div class="alert alert-{{ message[1] }}" role="alert">
        {{ message[0] }}
    </div>
    {% endfor %}
    <div class="total-credit">
        <p>總學分：{{ total_credit }}</p>
    </div>
    <div class="table-container">
        <table class="table">
            <thead>
                <tr>
                    <th>時間</th>
                    <th>課程代號</th>
                    <th>課程名稱</th>
                    <th>老師姓名</th>
                    <th>課程地點</th>
                    <th>必選修</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for course in table %}
                <tr>
                    <td>{{ course[0] }}</td>
                    <td>{{ course[1] }}</td>
                    <td>{{ course[2] }}</td>
                    <td>{{ course[3] }}</td>
                    <td>{{ course[4] }}</td>
                    <td>{{ "必修" if course[5] else "選修" }}</td>
                    <td>
                        <form action="{{ url_for('timetable.withdraw_course', course_id=course[1]) }}" method="post" {%
                            if course[5] %} onsubmit="return confirmWithdraw()" {% endif %}>
                            <button type="submit" class="btn-withdraw">退選</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script>
    function confirmWithdraw() {
        return confirm('此課程為必修，確定要退選此課程嗎？');
    }


    window.onload = () => {
        const queryString = window.location.search;
        const urlParams = new URLSearchParams(queryString);
        if (urlParams.get('msg') != null) {
            alert(urlParams.get('msg'));
        }
    }

</script>
{% endblock %}